import { AiFillStar } from 'react-icons/ai';
import nikeWhite from "../images/nikeImg.jpeg";
import blackWhite from "../images/BlackNikeIcon.jpeg";

const mockedData = [{
    id: 1,
    img: nikeWhite,
    title: "Nike Air Monarch IV",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "Sneakers",
    subcategory: "Latest",
    country: "France",
}, {
    id: 2,
    img: blackWhite,
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Oldest",
    country: "Uk",
}, {
    id: 3,
    img: blackWhite,
    title: "Nike Air Monarch IV",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Latest",
    country: "USA",
}, {
    id: 4,
    img: nikeWhite,
    title: "Nike Air Force",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Oldest",
    country: "Canada",
}, {
    id: 5,
    img: nikeWhite,
    title: "Nike Air Monarch IV",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Mid",
    country: "USA",
}, {
    id: 6,
    img: blackWhite,
    title: "Nike Air Vapormax ",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Latest",
    country: "France",
}, {
    id: 7,
    img: nikeWhite,
    title: "Nike Air IV",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Mid",
    country: "UK",
}, {
    id: 8,
    img: blackWhite,
    title: "Nike Air Plus IV",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Oldest",
    country: "Canada",
}, {
    id: 9,
    img: nikeWhite,
    title: "Nike Air Monarch Plus",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Mid",
    country: "USA",
}, {
    id: 10,
    img: nikeWhite,
    title: "Nike Force IV",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Oldest",
    country: "France",
}, {
    id: 11,
    img: blackWhite,
    title: "Nike Air Monarch IV",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Latest",
    country: "Uk",
}, {
    id: 12,
    img: nikeWhite,
    title: "Nike Air Monarch Force",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Latest",
    country: "France",
}, {
    id: 13,
    img: nikeWhite,
    title: "Nike Fire IV",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Mid",
    country: "USA",
},
, {
    id: 14,
    img: blackWhite,
    title: "Nike Fire V",
    star: <AiFillStar className='rating-star' />,
    reviews: "(123 reviews)",
    prevPrice: "$140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    subcategory: "Mid",
    country: "USA",
},
]

export default mockedData;